# Copyright (C) 2024 ASTRON (Netherlands Institute for Radio Astronomy)
# SPDX-License-Identifier: GPL-3.0-or-later

# At Astron GitLab, docker-in-docker jobs require a 'dind' tag.
.dind:
  tags:
    - dind

include: .gitlab-ci.common.yml
