# Copyright (C) 2020 ASTRON (Netherlands Institute for Radio Astronomy)
# SPDX-License-Identifier: GPL-3.0-or-later

workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_TITLE =~ /(?i)(^WIP.*)/ || $CI_MERGE_REQUEST_TITLE =~ /(?i)(^DRAFT.*)/'
      when: never
    - when: always

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.failable:
  retry:
    max: 1
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

.docker_only: &if_docker_only
  if: '$ONLY_BUILD_DOCKER != null'
.astron_repo: &if_astron_repo
  if: '$CI_SERVER_HOST == "git.astron.nl"'
.not_astron_repo: &if_not_astron_repo
  if: '$CI_SERVER_HOST != "git.astron.nl"'

stages:
  - prepare
  - build
  - linting
  - test
  - publish
  - pages

# Build the base image for git.astron
build-base:
  stage: prepare
  extends: .failable
  image: docker:stable
  script:
  - docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -f ./docker/ubuntu_20_04_base .
  rules:
    # Always run this job. Note that a duplicate pipeline is triggered when pushing commits to
    # a branch that has an open MR, see https://gitlab.com/gitlab-org/gitlab/-/issues/201845
    - if: '$CI_SERVER_HOST == "git.astron.nl"'
      when: always
    - when: never

# On the SKA repo - which does not have a docker cache - we need to push it to the gitlab registry which requires docker:dind
build-base-ska:
  stage: prepare
  image: docker:stable
  services:
  - docker:dind
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -f ./docker/ubuntu_20_04_base .
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  rules:
    - <<: *if_not_astron_repo

build-ubuntu18:
  stage: build
  extends: .failable
  needs: []
  script:
  - docker build -f ./docker/ubuntu_18_04 .
  rules:
    - <<: *if_astron_repo

build-no-idg:
  stage: build
  extends: .failable
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  before_script:
    - rm -r /usr/lib/cmake/*idg*
    - rm -r /usr/lib/cmake/*IDGAPITargets*
    - rm -r /usr/lib/*idg*
  script:
    - mkdir build
    - cd build
    - cmake -G Ninja ..
    - ninja
  rules:
    - <<: *if_docker_only
      when: never
    - <<: *if_astron_repo

build-debug:
  stage: build
  extends: .failable
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  script:
    - mkdir build && cd build
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-coverage" -DCMAKE_EXE_LINKER_FLAGS="-coverage" ..
    - ninja
    - ninja install
  artifacts:
    paths:
      - build
  rules:
    - <<: *if_docker_only
      when: never
    - when: on_success

build-release:
  stage: build
  extends: .failable
  image: docker:stable
  needs: ["build-base"]
  script:
    - docker build --build-arg BASE_TAG=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --tag dppp_lofar:${CI_COMMIT_SHORT_SHA} -f ./docker/ubuntu_20_04_dppp .
  rules:
    - <<: *if_astron_repo

# On the SKA repo - which does not have a docker cache - we need to push it to the gitlab registry which requires docker:dind
build-release-ska:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  needs: ["build-base-ska"]
  script:
    - docker build --build-arg BASE_TAG=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --tag dppp_lofar:${CI_COMMIT_SHORT_SHA} -f ./docker/ubuntu_20_04_dppp .
  rules:
    - <<: *if_not_astron_repo

build-doc:
  stage: build
  extends: .failable
  image: docker:stable
  needs: []
  before_script:
  - apk update
  - apk add doxygen cmake ninja python3 py3-pip
  - python3 -m pip install autosemver==0.5.5 jsonschema2rst==0.1.0 sphinx sphinx-rtd-theme
  script:
  - mkdir build && cd build
  - cmake -G Ninja ../docs
  - ninja doc userdoc
  artifacts: # Only for master the docs are published; for branches it may be useful to browse the artifacts
    paths:
    - build/docs
  rules:
    - <<: *if_docker_only
      when: never
    - <<: *if_astron_repo

linting:
  stage: linting
  extends: .failable
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  before_script:
    - pip3 install clang-format==9.0.0
  script:
    - ./scripts/run-clang-format.sh
  rules:
    - <<: *if_docker_only
      when: never
    - when: on_success

unit-test:
  stage: test
  extends: .failable
  needs: ["build-debug"]
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  before_script:
    - pip3 install gcovr
  script:
    - cd build
    - ninja # Needed when ran on different containers with different timestamps
    - ctest --output-on-failure -j$(($(nproc)/2 > 0 ? $(nproc)/2:1)) -L unit |& tee ctest.out
    # Check if ctest found any tests. ctest >= 3.18 has a --no-tests=error
    # option. Older versions require a manual check.
    - if grep -q 'No tests were found' ctest.out; then exit 1; fi
    # The line below will show the coverage in the logs which are used in the gitlab coverage. Common is included in this coverage report.
    - gcovr -j$(($(nproc)/2 > 0 ? $(nproc)/2:1)) -r ../ -e '.*/external/.*' -e '.*/test/.*' -e '.*/CompilerIdCXX/.*'
    # The line below will generate the json that is used for the total coverage which we report to SKA using badges.
    # It will be merged with the integration test coverage later.
    - gcovr -j$(($(nproc)/2 > 0 ? $(nproc)/2:1)) -r ../ -e '.*/external/.*' -e '.*/test/.*' -e '.*/CompilerIdCXX/.*' --json -o run-unit.json
  artifacts:
    paths:
      - build/run-unit.json
      - build/unittests.xml
    reports:
      junit: build/unittests.xml
  rules:
    - <<: *if_docker_only
      when: never
    - when: on_success

integration-test:
  stage: test
  extends: .failable
  needs: ["build-debug"]
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  before_script:
    - pip3 install gcovr h5py
  script:
    - cd build
    - ninja # Needed when ran on different containers with different timestamps
    - ctest --output-on-failure -j$(($(nproc)/2 > 0 ? $(nproc)/2:1)) -L integration |& tee ctest.out
    # Check if ctest found any tests. ctest >= 3.18 has a --no-tests=error
    # option. Older versions require a manual check.
    - if grep -q 'No tests were found' ctest.out; then exit 1; fi
    - gcovr -j$(($(nproc)/2 > 0 ? $(nproc)/2:1)) -r ../ -e '.*/external/.*' -e '.*/test/.*' -e '.*/CompilerIdCXX/.*' -e '.*/Common/.*' --json -o run-integration.json
  artifacts:
    paths:
      - build/run-integration.json
  rules:
    - <<: *if_docker_only
      when: never
    - when: on_success

check-stack:
  variables:
    # Pass commit hash to downstream pipeline
    DP3_TRIGGER_HASH: $CI_COMMIT_SHA
  stage: test
  needs: []
  trigger:
    project: RD/schaap-stack
    branch: master
    # This will mirror the status of the downstream pipeline
    strategy: depend
  rules:
    - <<: *if_docker_only
      when: never
    - <<: *if_not_astron_repo
      when: never
    # Only add job for a merge request event on git.astron.nl
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

publish-doc:
  stage: publish
  image: docker:stable
  needs: ["build-doc"]
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | base64 -d | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H dop288 > ~/.ssh/known_hosts
  script:
    - scp -r build/docs/* citt@dop288:DP3/
  rules:
    - <<: *if_docker_only
      when: never
    - <<: *if_not_astron_repo
      when: never
    - if: '$CI_COMMIT_BRANCH == "master"'

pages:
  stage: pages
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  needs: ["build-debug", "unit-test", "integration-test"]
  before_script:
    - apt-get update
    - apt-get -y install curl
    - pip3 install gcovr
  script:
    - mkdir -p .public/build/reports
    - cd .public
    - gcovr -j$(($(nproc)/2 > 0 ? $(nproc)/2:1)) -r ../ -a ../build/run-integration.json -a ../build/run-unit.json --xml -o build/reports/code-coverage.xml
    - gcovr -j$(($(nproc)/2 > 0 ? $(nproc)/2:1)) -r ../ -a ../build/run-integration.json -a ../build/run-unit.json --html --html-details -o index.html
    - cp ../build/unittests.xml build/reports/unit-tests.xml
    # Create and upload GitLab badges
    - chmod -R 700 ../CI
    - python3 ../CI/.produce-ci-metrics.py build/reports > ci-metrics.json
    - sh ../CI/ci-badges-func.sh
    - cd ..
    - mv .public public
  artifacts:
    paths:
      - public
    reports:
      cobertura: public/build/reports/code-coverage.xml
  rules:
    - <<: *if_docker_only
      when: never
    - when: on_success
