# Copyright (C) 2022 ASTRON (Netherlands Institute for Radio Astronomy)
# SPDX-License-Identifier: GPL-3.0-or-later

# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
    - cmake
    - doxygen
    - ninja-build
  jobs:
    pre_build:
      # Make 'doc' render as text, not inline (make sure to apply this patch also in local CI)
      - echo Patching $(find $HOME -path '*/jsonschema2rst/rst_utils.py')...
      - patch -p0 $(find $HOME -path '*/jsonschema2rst/rst_utils.py') < docs/rst_utils.py.patch
      - mkdir build
      # CMake converts conf.py.in into conf.py.
      - cmake -S docs/ -B build -G Ninja
      # Build doxygen documentation
      - cd build && ninja doc

sphinx:
  configuration: build/conf.py

python:
  install:
    - requirements: docs/requirements-docs.txt
