# Copyright (C) 2022 ASTRON (Netherlands Institute for Radio Astronomy)
# SPDX-License-Identifier: GPL-3.0-or-later

# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  # Convert conf.py.in into conf.py using CMake.
  apt_packages:
    - cmake
  jobs:
    pre_build:
      # Fix https://github.com/inspirehep/jsonschema2rst/issues/13
      - echo Patching $(find $HOME -path '*/jsonschema2rst/parser.py')...
      - patch -p0 $(find $HOME -path '*/jsonschema2rst/parser.py') < docs/parser.py.patch
      - mkdir build
      - cmake -S docs/ -B build

sphinx:
  configuration: build/conf.py

python:
  install:
    - requirements: docs/requirements-docs.txt
